# MCAR TEST

In [7]:
# #Loading required Libraries
# !pip install missingpy==0.2.0
# !pip install scikit-learn==1.1.2

# import sys
# import sklearn.neighbors._base
# sys.modules['sklearn.neighbors.base'] = sklearn.neighbors._base
# from missingpy import MissForest,KNNImputer
# import pandas as pd
# import numpy as np

In [8]:
import pandas as pd

In [9]:
#mount the gdrive
from google.colab import drive
drive.mount("/content/gdrive")

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).

In [10]:
df = pd.read_csv("/content/gdrive/MyDrive/Colab Notebooks/Exploratory_Data_Analysis/Dataset/housing_in_london_yearly_variables.csv")

In [11]:
# Display the first few rows of the dataset
df.head(5)

,code,area,date,median_salary,life_satisfaction,mean_salary,recycling_pct,population_size,number_of_jobs,area_size,no_of_houses,borough_flag
0,E09000001,city of london,1999-12-01,33020.0,NaN,48922,0,6581.0,NaN,NaN,NaN,1
1,E09000002,barking and dagenham,1999-12-01,21480.0,NaN,23620,3,162444.0,NaN,NaN,NaN,1
2,E09000003,barnet,1999-12-01,19568.0,NaN,23128,8,313469.0,NaN,NaN,NaN,1
3,E09000004,bexley,1999-12-01,18621.0,NaN,21386,18,217458.0,NaN,NaN,NaN,1
4,E09000005,brent,1999-12-01,18532.0,NaN,20911,6,260317.0,NaN,NaN,NaN,1

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1071 entries, 0 to 1070
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   code               1071 non-null   object
 1   area               1071 non-null   object
 2   date               1071 non-null   object
 3   median_salary      1049 non-null   float64
 4   life_satisfaction  352 non-null    float64
 5   mean_salary        1071 non-null   object
 6   recycling_pct      860 non-null    object
 7   population_size    1018 non-null   float64
 8   number_of_jobs     931 non-null    float64
 9   area_size          666 non-null    float64
 10  no_of_houses       666 non-null    float64
 11  borough_flag       1071 non-null   int64
dtypes: float64(6), int64(1), object(5)
memory usage: 100.5+ KB

In [13]:
df.describe()

,median_salary,life_satisfaction,population_size,number_of_jobs,area_size,no_of_houses,borough_flag
count,1049.000000,352.000000,1.018000e+03,9.310000e+02,6.660000e+02,6.660000e+02,1071.000000
mean,27977.792183,7.485057,6.042576e+06,3.188095e+06,3.724903e+05,8.814682e+05,0.647059
std,6412.807487,0.198451,1.526810e+07,8.058302e+06,2.157060e+06,3.690376e+06,0.478108
min,15684.000000,7.000000,6.581000e+03,4.700000e+04,3.150000e+02,5.009000e+03,0.000000
25%,23857.000000,7.350000,2.243458e+05,9.450000e+04,2.960000e+03,8.763550e+04,0.000000
50%,27441.000000,7.510000,2.946035e+05,1.570000e+05,4.323000e+03,1.024020e+05,1.000000
75%,30932.000000,7.640000,4.630098e+06,2.217000e+06,8.220000e+03,1.262760e+05,1.000000
max,61636.000000,7.960000,6.643555e+07,3.575000e+07,1.330373e+07,2.417217e+07,1.000000

In [14]:
# Check for missing values
missing_values = df.isnull().sum()

# Display missing values count for each column
print(missing_values)

code                   0
area                   0
date                   0
median_salary         22
life_satisfaction    719
mean_salary            0
recycling_pct        211
population_size       53
number_of_jobs       140
area_size            405
no_of_houses         405
borough_flag           0
dtype: int64

In [15]:
df.dtypes

code                  object
area                  object
date                  object
median_salary        float64
life_satisfaction    float64
mean_salary           object
recycling_pct         object
population_size      float64
number_of_jobs       float64
area_size            float64
no_of_houses         float64
borough_flag           int64
dtype: object

In [16]:
import numpy as np

In [17]:
# Preprocess data: selecting numeric data from dataset
df_numeric = df.select_dtypes(include=[np.number])
df_numeric

,median_salary,life_satisfaction,population_size,number_of_jobs,area_size,no_of_houses,borough_flag
0,33020.0,NaN,6581.0,NaN,NaN,NaN,1
1,21480.0,NaN,162444.0,NaN,NaN,NaN,1
2,19568.0,NaN,313469.0,NaN,NaN,NaN,1
3,18621.0,NaN,217458.0,NaN,NaN,NaN,1
4,18532.0,NaN,260317.0,NaN,NaN,NaN,1
...,...,...,...,...,...,...,...
1066,30446.0,NaN,NaN,NaN,NaN,NaN,0
1067,30500.0,NaN,NaN,NaN,NaN,NaN,0
1068,27434.0,NaN,NaN,NaN,NaN,NaN,0
1069,30000.0,NaN,NaN,NaN,NaN,NaN,0
1070,27500.0,NaN,NaN,NaN,NaN,NaN,0

# **Little MCAR test : Method 1**

Dropping those columns which have missing value more than or equal to 50%

In [18]:
# Drop columns with more than 50% missing values
missing_rate = df_numeric.isnull().mean()
print(missing_rate)
df_filtered = df_numeric.loc[:, missing_rate < 0.5]
df_filtered

median_salary        0.020542
life_satisfaction    0.671335
population_size      0.049486
number_of_jobs       0.130719
area_size            0.378151
no_of_houses         0.378151
borough_flag         0.000000
dtype: float64

,median_salary,population_size,number_of_jobs,area_size,no_of_houses,borough_flag
0,33020.0,6581.0,NaN,NaN,NaN,1
1,21480.0,162444.0,NaN,NaN,NaN,1
2,19568.0,313469.0,NaN,NaN,NaN,1
3,18621.0,217458.0,NaN,NaN,NaN,1
4,18532.0,260317.0,NaN,NaN,NaN,1
...,...,...,...,...,...,...
1066,30446.0,NaN,NaN,NaN,NaN,0
1067,30500.0,NaN,NaN,NaN,NaN,0
1068,27434.0,NaN,NaN,NaN,NaN,0
1069,30000.0,NaN,NaN,NaN,NaN,0
1070,27500.0,NaN,NaN,NaN,NaN,0

In [19]:
# Check if there's any numeric data to process
if df_filtered.empty:
    raise ValueError("No numeric columns with less than 50% missing data found in the dataset. Little's MCAR test cannot be performed.")

In [20]:
from scipy import stats

In [21]:
# Function to perform a simplified MCAR test
def mc_car_test(df):
    # Convert dataframe to numpy array
    data = df.to_numpy()

    # Count missing values
    missing_values = np.isnan(data)

    # If no missing values, return early
    if not np.any(missing_values):
        print("No missing values found. Data is MCAR by definition.")
        return

    # Calculate missing data pattern
    missing_patterns = np.sum(missing_values, axis=1)

    # Calculate statistics for missing data pattern
    unique_patterns, counts = np.unique(missing_patterns, return_counts=True)
    pattern_probabilities = counts / len(missing_patterns)

    # Perform chi-square test to check the pattern distribution
    chi2_stat, p_value = stats.chisquare(pattern_probabilities)

    print("MCAR Test Results:")
    print(f"Chi-square statistic: {chi2_stat:.4f}")
    print(f"P-value: {p_value:.4f}")

    if p_value > 0.05:
        print("The null hypothesis cannot be rejected. The data is MCAR.")
    else:
        print("The null hypothesis is rejected. The data is not MCAR.")

In [22]:
# Run the test on the filtered dataset
mc_car_test(df_filtered)

MCAR Test Results:
Chi-square statistic: 1.5396
P-value: 0.9085
The null hypothesis cannot be rejected. The data is MCAR.

# **Little MCAR test : Method 2**

In [23]:
from scipy.stats import chi2

In [24]:
def little_mcar_test(data):
    n = len(data)  # Number of observations
    groups = []

    # Identify columns with missing values and create a mask for them
    for col in data.columns:
        mask = data[col].isnull()
        if mask.any():
            groups.append(mask.astype(int).values.reshape(-1, 1))

    # Raise an error if no missing data is found
    if len(groups) == 0:
        raise ValueError("No missing data found.")

    # Concatenate the group masks into a single matrix
    r = np.concatenate(groups, axis=1)

    # Compute the group statistics
    group_stats = r.T @ r
    m = len(groups)  # Number of groups (columns with missing data)

    # Calculate degrees of freedom
    df = (n - 1) * m

    # Calculate the chi-squared statistic
    chi2_stat = group_stats.trace()

    # Calculate the p-value
    p_value = chi2.sf(chi2_stat, df)

    # Return the results
    return {
        "chi2_stat": chi2_stat,
        "degrees_of_freedom": df,
        "p_value": p_value
    }

In [25]:
# Run the MCAR test
result = little_mcar_test(df)

# Print the results
print(f"Chi-square statistic: {result['chi2_stat']}")
print(f"Degrees of freedom: {result['degrees_of_freedom']}")
print(f"P-value: {result['p_value']}")

# Hypothesis test result
if result['p_value'] > 0.05:
  print("The null hypothesis cannot be rejected. The data is MCAR.")
else:
  print("The null hypothesis is rejected. The data is not MCAR.")

Chi-square statistic: 1955
Degrees of freedom: 7490
P-value: 1.0
The null hypothesis cannot be rejected. The data is MCAR.

# **Little MCAR test : Method 3**

Using inbuilt functions

In [26]:
# Create missingness indicators
missingness_indicators = df.isnull().astype(int)
missingness_indicators

,code,area,date,median_salary,life_satisfaction,mean_salary,recycling_pct,population_size,number_of_jobs,area_size,no_of_houses,borough_flag
0,0,0,0,0,1,0,0,0,1,1,1,0
1,0,0,0,0,1,0,0,0,1,1,1,0
2,0,0,0,0,1,0,0,0,1,1,1,0
3,0,0,0,0,1,0,0,0,1,1,1,0
4,0,0,0,0,1,0,0,0,1,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
1066,0,0,0,0,1,0,1,1,1,1,1,0
1067,0,0,0,0,1,0,1,1,1,1,1,0
1068,0,0,0,0,1,0,1,1,1,1,1,0
1069,0,0,0,0,1,0,1,1,1,1,1,0
1070,0,0,0,0,1,0,1,1,1,1,1,0

In [27]:
# Add columns for missingness indicators
df['median_salary_missing'] = missingness_indicators['median_salary']
df['life_satisfaction_missing'] = missingness_indicators['life_satisfaction']
df['recycling_pct_missing'] = missingness_indicators['recycling_pct']
df['population_size_missing'] = missingness_indicators['population_size']
df['number_of_jobs_missing'] = missingness_indicators['number_of_jobs']
df['area_size_missing'] = missingness_indicators['area_size']
df['no_of_houses_missing'] = missingness_indicators['no_of_houses']

# Create a complete-case dataset (remove rows with any missing values)
complete_data = df.dropna()
complete_data

,code,area,date,median_salary,life_satisfaction,mean_salary,recycling_pct,population_size,number_of_jobs,area_size,no_of_houses,borough_flag,median_salary_missing,life_satisfaction_missing,recycling_pct_missing,population_size_missing,number_of_jobs_missing,area_size_missing,no_of_houses_missing
613,E09000002,barking and dagenham,2011-12-01,28201.0,7.05,33568,30,187029.0,54000.0,3780.0,71079.0,1,0,0,0,0,0,0,0
614,E09000003,barnet,2011-12-01,30237.0,7.43,33062,34,357538.0,147000.0,8675.0,139346.0,1,0,0,0,0,0,0,0
615,E09000004,bexley,2011-12-01,28638.0,7.42,31812,54,232774.0,78000.0,6429.0,95037.0,1,0,0,0,0,0,0,0
616,E09000005,brent,2011-12-01,26772.0,7.11,29609,37,312245.0,115000.0,4323.0,112083.0,1,0,0,0,0,0,0,0
617,E09000006,bromley,2011-12-01,28163.0,7.50,32863,50,310554.0,119000.0,15013.0,135036.0,1,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999,E09000031,waltham forest,2018-12-01,30298.0,7.46,32875,32,276700.0,88000.0,3881.0,103029.0,1,0,0,0,0,0,0,0
1000,E09000032,wandsworth,2018-12-01,34501.0,7.65,45317,23,326474.0,147000.0,3522.0,146162.0,1,0,0,0,0,0,0,0
1001,E09000033,westminster,2018-12-01,43015.0,7.66,63792,22,255324.0,775000.0,2203.0,124509.0,1,0,0,0,0,0,0,0
1008,E12000007,london,2018-12-01,38146.0,7.58,52629,33,8908081.0,6148000.0,159471.0,3556161.0,0,0,0,0,0,0,0,0
1013,E92000001,england,2018-12-01,29856.0,7.71,37313,44,55977178.0,30493000.0,13303728.0,24172166.0,0,0,0,0,0,0,0,0

In [28]:
import statsmodels.api as sm
from statsmodels.formula.api import logit

In [29]:
# Fit logistic regression for the missingness of 'median_salary'
formula = 'median_salary_missing ~ area_size + population_size + number_of_jobs + life_satisfaction + recycling_pct'
model = logit(formula, data=complete_data).fit()

Warning: Maximum number of iterations has been exceeded.
         Current function value: 0.000000
         Iterations: 35

/usr/local/lib/python3.10/dist-packages/statsmodels/discrete/discrete_model.py:227: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/usr/local/lib/python3.10/dist-packages/statsmodels/discrete/discrete_model.py:227: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/usr/local/lib/python3.10/dist-packages/statsmodels/discrete/discrete_model.py:227: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/usr/local/lib/python3.10/dist-packages/statsmodels/discrete/discrete_model.py:227: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/usr/local/lib/python3.10/dist-packages/statsmodels/discrete/discrete_model.py:227: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/usr/local/lib/python3.10/dist-packages/statsmodels/discrete/discrete_model.py:227: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/usr/local/lib/python3.10/dist-packages/statsmodels/discrete/discrete_model.py:227: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/usr/local/lib/python3.10/dist-packages/statsmodels/discrete/discrete_model.py:227: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/usr/local/lib/python3.10/dist-packages/statsmodels/discrete/discrete_model.py:227: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/usr/local/lib/python3.10/dist-packages/statsmodels/discrete/discrete_model.py:227: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/usr/local/lib/python3.10/dist-packages/statsmodels/discrete/discrete_model.py:227: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/usr/local/lib/python3.10/dist-packages/statsmodels/discrete/discrete_model.py:227: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/usr/local/lib/python3.10/dist-packages/statsmodels/discrete/discrete_model.py:227: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/usr/local/lib/python3.10/dist-packages/statsmodels/discrete/discrete_model.py:227: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/usr/local/lib/python3.10/dist-packages/statsmodels/discrete/discrete_model.py:227: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/usr/local/lib/python3.10/dist-packages/statsmodels/discrete/discrete_model.py:227: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/usr/local/lib/python3.10/dist-packages/statsmodels/discrete/discrete_model.py:227: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/usr/local/lib/python3.10/dist-packages/statsmodels/discrete/discrete_model.py:227: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/usr/local/lib/python3.10/dist-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "

In [30]:
# Check if any p-values are significant
if (model.pvalues < 0.05).any():
    print("Reject the null hypothesis: Data may not be MCAR.")
else:
    print("Fail to reject the null hypothesis: Data may be MCAR.")

Fail to reject the null hypothesis: Data may be MCAR.

# **Different imputation methods**

In [31]:
!pip install --upgrade scikit-learn fancyimpute

Requirement already satisfied: scikit-learn in /usr/local/lib/python3.10/dist-packages (1.3.2)
Collecting scikit-learn
  Downloading scikit_learn-1.5.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (13 kB)
Collecting fancyimpute
  Downloading fancyimpute-0.7.0.tar.gz (25 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy>=1.19.5 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (1.26.4)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (1.13.1)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (3.5.0)
Collecting knnimpute>=0.1.0 (from fancyimpute)
  Downloading knnimpute-0.1.0.tar.gz (8.3 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: cvxpy in /usr/local/lib/python3.10/dist-packages (from fancyimpute) (1.5.3)
Requirement already satisfied: cvxopt in /usr/local/lib/python3.10/dist-packages (from fancyimpute) (1.3.2)
Requirement already satisfied: pytest in /usr/local/lib/python3.10/dist-packages (from fancyimpute) (7.4.4)
Collecting nose (from fancyimpute)
  Downloading nose-1.3.7-py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from knnimpute>=0.1.0->fancyimpute) (1.16.0)
Requirement already satisfied: osqp>=0.6.2 in /usr/local/lib/python3.10/dist-packages (from cvxpy->fancyimpute) (0.6.7.post0)
Requirement already satisfied: ecos>=2 in /usr/local/lib/python3.10/dist-packages (from cvxpy->fancyimpute) (2.0.14)
Requirement already satisfied: clarabel>=0.5.0 in /usr/local/lib/python3.10/dist-packages (from cvxpy->fancyimpute) (0.9.0)
Requirement already satisfied: scs>=3.2.4.post1 in /usr/local/lib/python3.10/dist-packages (from cvxpy->fancyimpute) (3.2.7)
Requirement already satisfied: iniconfig in /usr/local/lib/python3.10/dist-packages (from pytest->fancyimpute) (2.0.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from pytest->fancyimpute) (24.1)
Requirement already satisfied: pluggy<2.0,>=0.12 in /usr/local/lib/python3.10/dist-packages (from pytest->fancyimpute) (1.5.0)
Requirement already satisfied: exceptiongroup>=1.0.0rc8 in /usr/local/lib/python3.10/dist-packages (from pytest->fancyimpute) (1.2.2)
Requirement already satisfied: tomli>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from pytest->fancyimpute) (2.0.1)
Requirement already satisfied: qdldl in /usr/local/lib/python3.10/dist-packages (from osqp>=0.6.2->cvxpy->fancyimpute) (0.1.7.post4)
Downloading scikit_learn-1.5.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (13.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.3/13.3 MB 76.2 MB/s eta 0:00:00
Downloading nose-1.3.7-py3-none-any.whl (154 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 154.7/154.7 kB 9.9 MB/s eta 0:00:00
Building wheels for collected packages: fancyimpute, knnimpute
  Building wheel for fancyimpute (setup.py) ... done
  Created wheel for fancyimpute: filename=fancyimpute-0.7.0-py3-none-any.whl size=29880 sha256=92e61106da5606928278a7425f8cf0f7dd06069a6eabf82f7ca8e92de7972ffe
  Stored in directory: /root/.cache/pip/wheels/7b/0c/d3/ee82d1fbdcc0858d96434af108608d01703505d453720c84ed
  Building wheel for knnimpute (setup.py) ... done
  Created wheel for knnimpute: filename=knnimpute-0.1.0-py3-none-any.whl size=11330 sha256=d642bf04657362ad5fc683de2c377555ad10a95ada0b9a91e3f6f6b91c720bb5
  Stored in directory: /root/.cache/pip/wheels/46/06/a5/45a724630562413c374e29c08732411d496092408b3a7bf754
Successfully built fancyimpute knnimpute
Installing collected packages: nose, knnimpute, scikit-learn, fancyimpute
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.3.2
    Uninstalling scikit-learn-1.3.2:
      Successfully uninstalled scikit-learn-1.3.2
Successfully installed fancyimpute-0.7.0 knnimpute-0.1.0 nose-1.3.7 scikit-learn-1.5.2

In [32]:
from fancyimpute import KNN, IterativeImputer

In [33]:
# Select only numeric columns for imputation
numeric_df = df.select_dtypes(include=[np.number])
numeric_df

,median_salary,life_satisfaction,population_size,number_of_jobs,area_size,no_of_houses,borough_flag,median_salary_missing,life_satisfaction_missing,recycling_pct_missing,population_size_missing,number_of_jobs_missing,area_size_missing,no_of_houses_missing
0,33020.0,NaN,6581.0,NaN,NaN,NaN,1,0,1,0,0,1,1,1
1,21480.0,NaN,162444.0,NaN,NaN,NaN,1,0,1,0,0,1,1,1
2,19568.0,NaN,313469.0,NaN,NaN,NaN,1,0,1,0,0,1,1,1
3,18621.0,NaN,217458.0,NaN,NaN,NaN,1,0,1,0,0,1,1,1
4,18532.0,NaN,260317.0,NaN,NaN,NaN,1,0,1,0,0,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1066,30446.0,NaN,NaN,NaN,NaN,NaN,0,0,1,1,1,1,1,1
1067,30500.0,NaN,NaN,NaN,NaN,NaN,0,0,1,1,1,1,1,1
1068,27434.0,NaN,NaN,NaN,NaN,NaN,0,0,1,1,1,1,1,1
1069,30000.0,NaN,NaN,NaN,NaN,NaN,0,0,1,1,1,1,1,1
1070,27500.0,NaN,NaN,NaN,NaN,NaN,0,0,1,1,1,1,1,1

In [45]:
# Check for missing values
missing_values = numeric_df.isnull().sum()

# Display missing values count for each column
print(missing_values)

median_salary                 22
life_satisfaction            719
population_size               53
number_of_jobs               140
area_size                    405
no_of_houses                 405
borough_flag                   0
median_salary_missing          0
life_satisfaction_missing      0
recycling_pct_missing          0
population_size_missing        0
number_of_jobs_missing         0
area_size_missing              0
no_of_houses_missing           0
dtype: int64

In [34]:
# Mean Imputation
mean_filled = numeric_df.fillna(numeric_df.mean())
mean_filled

,median_salary,life_satisfaction,population_size,number_of_jobs,area_size,no_of_houses,borough_flag,median_salary_missing,life_satisfaction_missing,recycling_pct_missing,population_size_missing,number_of_jobs_missing,area_size_missing,no_of_houses_missing
0,33020.0,7.485057,6.581000e+03,3.188095e+06,372490.27027,881468.15015,1,0,1,0,0,1,1,1
1,21480.0,7.485057,1.624440e+05,3.188095e+06,372490.27027,881468.15015,1,0,1,0,0,1,1,1
2,19568.0,7.485057,3.134690e+05,3.188095e+06,372490.27027,881468.15015,1,0,1,0,0,1,1,1
3,18621.0,7.485057,2.174580e+05,3.188095e+06,372490.27027,881468.15015,1,0,1,0,0,1,1,1
4,18532.0,7.485057,2.603170e+05,3.188095e+06,372490.27027,881468.15015,1,0,1,0,0,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1066,30446.0,7.485057,6.042576e+06,3.188095e+06,372490.27027,881468.15015,0,0,1,1,1,1,1,1
1067,30500.0,7.485057,6.042576e+06,3.188095e+06,372490.27027,881468.15015,0,0,1,1,1,1,1,1
1068,27434.0,7.485057,6.042576e+06,3.188095e+06,372490.27027,881468.15015,0,0,1,1,1,1,1,1
1069,30000.0,7.485057,6.042576e+06,3.188095e+06,372490.27027,881468.15015,0,0,1,1,1,1,1,1
1070,27500.0,7.485057,6.042576e+06,3.188095e+06,372490.27027,881468.15015,0,0,1,1,1,1,1,1

In [48]:
# Check for missing values
missing_values = mean_filled.isnull().sum()

# Display missing values count for each column
print(missing_values)

median_salary                0
life_satisfaction            0
population_size              0
number_of_jobs               0
area_size                    0
no_of_houses                 0
borough_flag                 0
median_salary_missing        0
life_satisfaction_missing    0
recycling_pct_missing        0
population_size_missing      0
number_of_jobs_missing       0
area_size_missing            0
no_of_houses_missing         0
dtype: int64

In [35]:
# Median Imputation
median_filled = numeric_df.fillna(numeric_df.median())
median_filled

,median_salary,life_satisfaction,population_size,number_of_jobs,area_size,no_of_houses,borough_flag,median_salary_missing,life_satisfaction_missing,recycling_pct_missing,population_size_missing,number_of_jobs_missing,area_size_missing,no_of_houses_missing
0,33020.0,7.51,6581.0,157000.0,4323.0,102402.0,1,0,1,0,0,1,1,1
1,21480.0,7.51,162444.0,157000.0,4323.0,102402.0,1,0,1,0,0,1,1,1
2,19568.0,7.51,313469.0,157000.0,4323.0,102402.0,1,0,1,0,0,1,1,1
3,18621.0,7.51,217458.0,157000.0,4323.0,102402.0,1,0,1,0,0,1,1,1
4,18532.0,7.51,260317.0,157000.0,4323.0,102402.0,1,0,1,0,0,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1066,30446.0,7.51,294603.5,157000.0,4323.0,102402.0,0,0,1,1,1,1,1,1
1067,30500.0,7.51,294603.5,157000.0,4323.0,102402.0,0,0,1,1,1,1,1,1
1068,27434.0,7.51,294603.5,157000.0,4323.0,102402.0,0,0,1,1,1,1,1,1
1069,30000.0,7.51,294603.5,157000.0,4323.0,102402.0,0,0,1,1,1,1,1,1
1070,27500.0,7.51,294603.5,157000.0,4323.0,102402.0,0,0,1,1,1,1,1,1

In [49]:
# Check for missing values
missing_values = median_filled.isnull().sum()

# Display missing values count for each column
print(missing_values)

median_salary                0
life_satisfaction            0
population_size              0
number_of_jobs               0
area_size                    0
no_of_houses                 0
borough_flag                 0
median_salary_missing        0
life_satisfaction_missing    0
recycling_pct_missing        0
population_size_missing      0
number_of_jobs_missing       0
area_size_missing            0
no_of_houses_missing         0
dtype: int64

In [36]:
# Mode Imputation
mode_filled = numeric_df.fillna(numeric_df.mode().iloc[0])
mode_filled

,median_salary,life_satisfaction,population_size,number_of_jobs,area_size,no_of_houses,borough_flag,median_salary_missing,life_satisfaction_missing,recycling_pct_missing,population_size_missing,number_of_jobs_missing,area_size_missing,no_of_houses_missing
0,33020.0,7.54,6581.0,80000.0,315.0,5374.0,1,0,1,0,0,1,1,1
1,21480.0,7.54,162444.0,80000.0,315.0,5374.0,1,0,1,0,0,1,1,1
2,19568.0,7.54,313469.0,80000.0,315.0,5374.0,1,0,1,0,0,1,1,1
3,18621.0,7.54,217458.0,80000.0,315.0,5374.0,1,0,1,0,0,1,1,1
4,18532.0,7.54,260317.0,80000.0,315.0,5374.0,1,0,1,0,0,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1066,30446.0,7.54,223776.0,80000.0,315.0,5374.0,0,0,1,1,1,1,1,1
1067,30500.0,7.54,223776.0,80000.0,315.0,5374.0,0,0,1,1,1,1,1,1
1068,27434.0,7.54,223776.0,80000.0,315.0,5374.0,0,0,1,1,1,1,1,1
1069,30000.0,7.54,223776.0,80000.0,315.0,5374.0,0,0,1,1,1,1,1,1
1070,27500.0,7.54,223776.0,80000.0,315.0,5374.0,0,0,1,1,1,1,1,1

In [50]:
# Check for missing values
missing_values = mode_filled.isnull().sum()

# Display missing values count for each column
print(missing_values)

median_salary                0
life_satisfaction            0
population_size              0
number_of_jobs               0
area_size                    0
no_of_houses                 0
borough_flag                 0
median_salary_missing        0
life_satisfaction_missing    0
recycling_pct_missing        0
population_size_missing      0
number_of_jobs_missing       0
area_size_missing            0
no_of_houses_missing         0
dtype: int64

In [66]:
# KNN Imputation
# Select numeric columns for imputation
numeric_columns = numeric_df.select_dtypes(include=['number']).columns

# Perform KNN imputation on the selected numeric columns
knn_imputer = KNN(k=5)  # Set the number of neighbors as needed
df[numeric_columns] = knn_imputer.fit_transform(df[numeric_columns])

# Display the imputed DataFrame
df.head()

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)
/usr/local/lib/python3.10/dist-packages/fancyimpute/solver.py:55: UserWarning: Input matrix is not missing any values
  warnings.warn("Input matrix is not missing any values")

Imputing row 1/1071 with 0 missing, elapsed time: 0.190
Imputing row 101/1071 with 0 missing, elapsed time: 0.190
Imputing row 201/1071 with 0 missing, elapsed time: 0.191
Imputing row 301/1071 with 0 missing, elapsed time: 0.191
Imputing row 401/1071 with 0 missing, elapsed time: 0.191
Imputing row 501/1071 with 0 missing, elapsed time: 0.191
Imputing row 601/1071 with 0 missing, elapsed time: 0.192
Imputing row 701/1071 with 0 missing, elapsed time: 0.192
Imputing row 801/1071 with 0 missing, elapsed time: 0.192
Imputing row 901/1071 with 0 missing, elapsed time: 0.192
Imputing row 1001/1071 with 0 missing, elapsed time: 0.193

,code,area,date,median_salary,life_satisfaction,mean_salary,recycling_pct,population_size,number_of_jobs,area_size,no_of_houses,borough_flag,median_salary_missing,life_satisfaction_missing,recycling_pct_missing,population_size_missing,number_of_jobs_missing,area_size_missing,no_of_houses_missing
0,E09000001,city of london,1999-12-01,33020.0,7.681440,48922,0,6581.0,651835.239856,315.000009,5122.123188,1.0,0.0,1.0,0.0,0.0,1.0,1.0,1.0
1,E09000002,barking and dagenham,1999-12-01,21480.0,7.527333,23620,3,162444.0,262134.726142,2721.468023,74838.417507,1.0,0.0,1.0,0.0,0.0,1.0,1.0,1.0
2,E09000003,barnet,1999-12-01,19568.0,7.392473,23128,8,313469.0,134029.823282,6809.129663,123683.305769,1.0,0.0,1.0,0.0,0.0,1.0,1.0,1.0
3,E09000004,bexley,1999-12-01,18621.0,7.648711,21386,18,217458.0,74915.660032,5692.462633,93157.896747,1.0,0.0,1.0,0.0,0.0,1.0,1.0,1.0
4,E09000005,brent,1999-12-01,18532.0,7.418609,20911,6,260317.0,86750.395301,3811.976600,98470.116249,1.0,0.0,1.0,0.0,0.0,1.0,1.0,1.0

In [67]:
# Check for missing values
missing_values = df.isnull().sum()

# Display missing values count for each column
print(missing_values)

code                           0
area                           0
date                           0
median_salary                  0
life_satisfaction              0
mean_salary                    0
recycling_pct                211
population_size                0
number_of_jobs                 0
area_size                      0
no_of_houses                   0
borough_flag                   0
median_salary_missing          0
life_satisfaction_missing      0
recycling_pct_missing          0
population_size_missing        0
number_of_jobs_missing         0
area_size_missing              0
no_of_houses_missing           0
dtype: int64

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

KNN imputer does not work for categorical data thus we need to encode it first in order to use KNN imputation and then apply it.

In [63]:
# Encode categorical columns
df_encoded = pd.get_dummies(df, drop_first=True)

# Perform imputation on the encoded DataFrame
df_knn_imputed = pd.DataFrame(KNN(k=5).fit_transform(df_encoded), columns=df_encoded.columns)

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)
/usr/local/lib/python3.10/dist-packages/fancyimpute/solver.py:55: UserWarning: Input matrix is not missing any values
  warnings.warn("Input matrix is not missing any values")

Imputing row 1/1071 with 0 missing, elapsed time: 7.191
Imputing row 101/1071 with 0 missing, elapsed time: 7.193
Imputing row 201/1071 with 0 missing, elapsed time: 7.194
Imputing row 301/1071 with 0 missing, elapsed time: 7.196
Imputing row 401/1071 with 0 missing, elapsed time: 7.198
Imputing row 501/1071 with 0 missing, elapsed time: 7.199
Imputing row 601/1071 with 0 missing, elapsed time: 7.200
Imputing row 701/1071 with 0 missing, elapsed time: 7.201
Imputing row 801/1071 with 0 missing, elapsed time: 7.202
Imputing row 901/1071 with 0 missing, elapsed time: 7.203
Imputing row 1001/1071 with 0 missing, elapsed time: 7.205

In [68]:
# Check for missing values
missing_values = df_knn_imputed.isnull().sum()

# Display missing values count for each column
print(missing_values)

median_salary        0
life_satisfaction    0
population_size      0
number_of_jobs       0
area_size            0
                    ..
recycling_pct_6      0
recycling_pct_7      0
recycling_pct_8      0
recycling_pct_9      0
recycling_pct_na     0
Length: 1230, dtype: int64

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

In [71]:
# Perform Missing Forest imputation (Iterative Imputer)
# Select numeric columns for imputation
numeric_columns = df.select_dtypes(include=['number']).columns

# Perform Missing Forest imputation (Iterative Imputer) on numeric columns
missing_forest_imputer = IterativeImputer()
df[numeric_columns] = missing_forest_imputer.fit_transform(df[numeric_columns])

# Display the imputed DataFrame
df.head()

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

,code,area,date,median_salary,life_satisfaction,mean_salary,recycling_pct,population_size,number_of_jobs,area_size,no_of_houses,borough_flag,median_salary_missing,life_satisfaction_missing,recycling_pct_missing,population_size_missing,number_of_jobs_missing,area_size_missing,no_of_houses_missing
0,E09000001,city of london,1999-12-01,33020.0,7.681440,48922,0,6581.0,651835.239856,315.000009,5122.123188,1.0,0.0,1.0,0.0,0.0,1.0,1.0,1.0
1,E09000002,barking and dagenham,1999-12-01,21480.0,7.527333,23620,3,162444.0,262134.726142,2721.468023,74838.417507,1.0,0.0,1.0,0.0,0.0,1.0,1.0,1.0
2,E09000003,barnet,1999-12-01,19568.0,7.392473,23128,8,313469.0,134029.823282,6809.129663,123683.305769,1.0,0.0,1.0,0.0,0.0,1.0,1.0,1.0
3,E09000004,bexley,1999-12-01,18621.0,7.648711,21386,18,217458.0,74915.660032,5692.462633,93157.896747,1.0,0.0,1.0,0.0,0.0,1.0,1.0,1.0
4,E09000005,brent,1999-12-01,18532.0,7.418609,20911,6,260317.0,86750.395301,3811.976600,98470.116249,1.0,0.0,1.0,0.0,0.0,1.0,1.0,1.0

In [72]:
# Check for missing values
missing_values = df.isnull().sum()

# Display missing values count for each column
print(missing_values)

code                           0
area                           0
date                           0
median_salary                  0
life_satisfaction              0
mean_salary                    0
recycling_pct                211
population_size                0
number_of_jobs                 0
area_size                      0
no_of_houses                   0
borough_flag                   0
median_salary_missing          0
life_satisfaction_missing      0
recycling_pct_missing          0
population_size_missing        0
number_of_jobs_missing         0
area_size_missing              0
no_of_houses_missing           0
dtype: int64

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

Missing Forest imputer does not work for categorical data thus we need to encode it first in order to use Missing Forest imputation and then apply it.

In [76]:
# Iterative Imputation
iterative_imputer = IterativeImputer()
iterative_filled = iterative_imputer.fit_transform(numeric_df)
iterative_filled_df = pd.DataFrame(iterative_filled, columns=numeric_df.columns)
iterative_filled_df

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

,median_salary,life_satisfaction,population_size,number_of_jobs,area_size,no_of_houses,borough_flag,median_salary_missing,life_satisfaction_missing,recycling_pct_missing,population_size_missing,number_of_jobs_missing,area_size_missing,no_of_houses_missing
0,33020.0,7.546422,6.581000e+03,1.348383e+05,-1.690380e+05,-1.087961e+04,1.0,0.0,1.0,0.0,0.0,1.0,1.0,1.0
1,21480.0,7.544629,1.624440e+05,-3.717981e+04,1.808396e+04,6.636956e+04,1.0,0.0,1.0,0.0,0.0,1.0,1.0,1.0
2,19568.0,7.544568,3.134690e+05,-7.328608e+02,8.083859e+04,1.332453e+05,1.0,0.0,1.0,0.0,0.0,1.0,1.0,1.0
3,18621.0,7.544216,2.174580e+05,-7.128962e+04,6.860180e+04,9.259103e+04,1.0,0.0,1.0,0.0,0.0,1.0,1.0,1.0
4,18532.0,7.544281,2.603170e+05,-5.100683e+04,8.060930e+04,1.111792e+05,1.0,0.0,1.0,0.0,0.0,1.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1066,30446.0,7.642789,6.037481e+06,3.205152e+06,1.395752e+06,2.596450e+06,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0
1067,30500.0,7.642800,6.037411e+06,3.206263e+06,1.395093e+06,2.596378e+06,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0
1068,27434.0,7.642199,6.041371e+06,3.143202e+06,1.432525e+06,2.600437e+06,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0
1069,30000.0,7.642702,6.038057e+06,3.195979e+06,1.401197e+06,2.597040e+06,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0
1070,27500.0,7.642211,6.041286e+06,3.144559e+06,1.431720e+06,2.600350e+06,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0

In [77]:
# Check for missing values
missing_values = iterative_filled_df.isnull().sum()

# Display missing values count for each column
print(missing_values)

median_salary                0
life_satisfaction            0
population_size              0
number_of_jobs               0
area_size                    0
no_of_houses                 0
borough_flag                 0
median_salary_missing        0
life_satisfaction_missing    0
recycling_pct_missing        0
population_size_missing      0
number_of_jobs_missing       0
area_size_missing            0
no_of_houses_missing         0
dtype: int64

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)